### ISSUE TITLE
 Syntax error: Unterminated quoted string. ERROR [carbonyl-terminal  7/11] RUN echo "printf

### ISSUE THREAD

**Issue by SonosInc** [niutech/carbonyl-terminal#1]
Hello!
Found an error in the Dockerfile:
RUN echo "printf '\\033]2;Carbonyl\\033\\\\'; [ -n \"\$TMUX\" ] && /carbonyl/carbonyl --no-sandbox --disable-dev-shm-usage --user-data-dir=/carbonyl/data --incognito \${START_PAGE:-$START_PAGE} || tmux; **exit'** > /carbonyl/data/.profile

Edit to:
RUN echo "printf '\\033]2;Carbonyl\\033\\\\'; [ -n \"\$TMUX\" ] && /carbonyl/carbonyl --no-sandbox --disable-dev-shm-usage --user-data-dir=/carbonyl/data --incognito \${START_PAGE:-$START_PAGE} || tmux; **exit"** > /carbonyl/data/.profile

**Comment by niutech** [comment]
Fixed, thank you!
